stages:
  process_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - data_source/Iris.csv
    outs:
      - data/raw/Iris.csv

  data_split:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - data/raw/Iris.csv
      - src/split_data.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train_test:
    cmd: python src/train_test.py --config=params.yaml
    deps:
      - src/train_test.py
      - data/processed/train.csv
      - data/processed/test.csv
    params:
      - estimators.DecisionTreeClassifier.params.criterion
      - estimators.DecisionTreeClassifier.params.max_depth

    metrics:
      - report/scores.json:
          cache: false
      - report/params.json:
          cache: false
      
    outs:
      - saved_models/model.joblib