name: Iris Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python Setup
        uses: actions/setup-python@v2
        with: 
          python-version: 3.11.5
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Run Tox
      #   run: |
      #     tox
      - name: Run dvc.repro
        run: |
          dvc pull
          dvc repro
